== Channel Groups APIs

==== channel_group_list_groups

Lists all groups 

====== Parameters

* namespace (String) (Optional)

  namespace argument if provided, lists groups within a namespace


* callback (Function) (Optional)

  callback is invoked on successful completion of method and gets result as argument.

* error (Function) (Optional)

  error is invoked on error response from backend, or a network error.



==== channel_group_list_channels

Lists channels in a group.

====== Parameters

* namespace (String) (Optional) 

  namespace argument if provided, is used to specify channel group within a namespace.
  

* channel_group (String) (Required)

  channel group for which to list the channels

* callback (Optional) 

  callback is invoked on successful completion of method and gets result as argument.

* error (Optional) 

  error is invoked on error response from backend, or a network error.

==== channel_group_remove_channel

====== Parameters

* namespace 

  namespace argument if provided, specifes channel group within a namespace

* channel_group (String) (Required)

  channel group from which to remove the channel

* channel/channels (String/Comma separated list/Array) (Required)

  Channel/Channels specifies channel or channels to be removed from the channel group.

* callback (Optional) 

  callback is invoked on successful completion of method and gets result as argument.

* error (Optional) 

  error is invoked on error response from backend, or a network error.
  
==== channel_group_remove_group

====== Parameters

* namespace 

  namespace argument if provided, specifies group to be removed within a namespace

* channel_group (String) (Required)

  channel group to be removed

* callback (Optional) 

  callback is invoked on successful completion of method and gets result as argument.

* error (Optional) 

  error is invoked on error response from backend, or a network error.

==== channel_group_add_channel

Adds channel/channels to a channel group.

====== Parameters

* namespace 

  namespace argument if provided, specifes channel group within a namespace

* channel_group (String) (Required)

  channel group to which to add the channel

* channel/channels (String/Comma separated list/Array) (Required)

  Channel/Channels specifies channel or channels to be added to the channel group.


* callback 

  callback is invoked on successful completion of method and gets result as argument.

* error 

  error is invoked on error response from backend, or a network error.


==== channel_group_list_namespaces

Lists all namespaces for the subscribe key.

====== Parameters

* callback (Optional) 

  callback is invoked on successful completion of method and gets result as argument.

* error (Function) (Optional) 

  error is invoked on error response from backend, or a network error.

==== channel_group_remove_namespace

Removes a namespace corresponding to a subscribe key.

====== Parameters

* namespace 

  namespace to be removed.


* callback (Function) (Optional)

  callback is invoked on successful completion of method and gets result as argument.

* error (Function) (Optional)

  error is invoked on error response from backend, or a network error.
  
  
==== channel_group_cloak

TODO: I need to recall what this is used for. 

====== Parameters


* callback (Function) (Optional)

  callback is invoked on successful completion of method and gets result as argument.

* error (Function) (Optional) 

  error is invoked on error response from backend, or a network error.
  
=== New argument for Subscribe

  New argument "channel_group" gets added to subscribe method. Specifying either channel or channel_group is mandatory.
  channel_group can be a string, comma separated list, or an array.
  
=== New argument for Grant, Revoke, Audit

  New argument "channel_group" gets added to all PAM methods. Specifying either channel or channel_group is mandatory.
  channel_group can be a string, comma separated list, or an array.
